# Generated by Django 5.0.1 on 2024-01-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='motto',
            field=models.TextField(default='Hi, welcome to my projects folder..'),
        ),
    ]
