# Generated by Django 5.0.1 on 2024-02-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_is_admin_user_is_authorized'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recent_visits', models.IntegerField(default=0)),
                ('recent_demos', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
