# Generated by Django 5.0.1 on 2024-01-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_demo',
            field=models.BooleanField(default=True),
        ),
    ]
