# Generated by Django 5.0.1 on 2024-01-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_is_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField()),
                ('css', models.TextField()),
                ('js', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
