# Generated by Django 5.0.1 on 2024-01-13 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
