# Generated by Django 5.0.1 on 2024-01-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_owner_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='margin_left',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='margin_top',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='scale',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
