# Generated by Django 5.0.1 on 2024-01-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_project_margin_left_project_margin_top_project_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='margin_left',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='margin_top',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='scale',
            field=models.FloatField(),
        ),
    ]
