# Generated by Django 5.0.1 on 2024-01-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_project_margin_left_alter_project_margin_top_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=32),
        ),
    ]
