# Generated by Django 5.0.1 on 2024-01-13 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_project_booked_marked_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='booked_marked_users',
            new_name='bookmarks',
        ),
    ]
