# Generated by Django 5.0.1 on 2024-01-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_booked_marked_users_project_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='app.user'),
        ),
    ]
