# Generated by Django 5.0.1 on 2024-01-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_project_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='bookmarks',
            field=models.ManyToManyField(related_name='bookmarked_projects', to='app.user'),
        ),
    ]
