# Generated by Django 5.0.1 on 2024-01-15 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_follows'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follows',
            new_name='Follow',
        ),
    ]
