# Generated by Django 5.0.1 on 2024-01-15 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_follows_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='following',
            new_name='followee',
        ),
    ]
