# Generated by Django 5.0.1 on 2024-01-15 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_following_follow_followee'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(related_name='followee', to='app.user'),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
