# Generated by Django 5.0.1 on 2024-01-15 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_user_followers_delete_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(related_name='followees', to='app.user'),
        ),
    ]
