# Generated by Django 5.0.1 on 2024-01-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_landingprojects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleProject',
        ),
        migrations.DeleteModel(
            name='LandingProjects',
        ),
        migrations.AddField(
            model_name='project',
            name='is_example',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='is_landing',
            field=models.BooleanField(default=False),
        ),
    ]
