# Generated by Django 5.0.1 on 2024-01-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_delete_exampleproject_delete_landingprojects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='motto',
            field=models.TextField(default='Hi, I haven not created a folder motto yet.'),
        ),
    ]
