# Generated by Django 5.0.1 on 2024-01-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_user_motto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='motto',
            field=models.TextField(default='Hi, I have not yet created a folder encapsultion..'),
        ),
    ]
