# Generated by Django 5.0.1 on 2024-01-18 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_project_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
